// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOrder struct {
	Code  string `json:"code"`
	Name  string `json:"name"`
	Price int    `json:"price"`
	Total int    `json:"total"`
}

type NewProduct struct {
	Code  string `json:"code"`
	Name  string `json:"name"`
	Price int    `json:"price"`
}

type Order struct {
	ID    string `json:"id"`
	Code  string `json:"code"`
	Name  string `json:"name"`
	Price int    `json:"price"`
	Total int    `json:"total"`
}

type Product struct {
	ID    string `json:"id"`
	Code  string `json:"code"`
	Name  string `json:"name"`
	Price int    `json:"price"`
}
