package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"lab/productService/apiGraphql/graph/model"
	"lab/productService/internal/product"
	"strconv"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	inputProduct := product.Product{Name: input.Name, Price: float64(input.Price)}
	p, _ := r.AppProduct.CreateProduct(inputProduct)
	return &model.Product{ID: strconv.Itoa(p.Id), Name: input.Name, Price: input.Price}, nil
}

// GetProducts is the resolver for the getProducts field.
func (r *queryResolver) GetProducts(ctx context.Context) ([]*model.Product, error) {
	var productsForApi []*model.Product
	ps, _ := r.AppProduct.AllListProducts()
	fmt.Println(ps)
	for _, i := range ps {
		p := model.Product{Name: i.Name, Price: int(i.Price)}
		productsForApi = append(productsForApi, &p)
	}
	return productsForApi, nil
}

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, code string) (*model.Product, error) {
	p, _ := r.AppProduct.GetProduct(code)
	return &model.Product{Name: p.Name, Price: int(p.Price)}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
